# Database configuration
# JDBC host (default: 127.0.0.1)
db.host=127.0.0.1
# JDBC port (default: 3306)
db.port=3306
# Database name (default: leave empty to connect to server/root)
db.name=payrollsystem_db
# Database user
db.user=root
# Database password
db.password=DF.w}=;$CLn+84?m]r(M%Q

